# Generated by Django 5.2.8 on 2025-11-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='platform',
            name='slug',
            field=models.SlugField(default='temp-slug', unique=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='logo',
            field=models.CharField(default='🔗', max_length=10),
        ),
    ]
