# Generated by Django 5.2.8 on 2025-11-13 12:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_remove_link_thumbnail_platform_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='title',
        ),
        migrations.AddField(
            model_name='link',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='name',
            field=models.CharField(default='Unnamed Link', max_length=100),
            preserve_default=False,
        ),
    ]
