# Generated by Django 5.2.7 on 2025-12-02 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_alter_link_name_alter_link_platform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='links.platform')),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='links.folder'),
        ),
    ]
