# Generated by Django 5.2.8 on 2025-12-02 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_folder_link_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_links', to='links.folder'),
        ),
    ]
