# Generated by Django 5.2.8 on 2025-12-04 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_alter_link_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='link',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='links.folder'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='platform_logos/'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='platform',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
