# Generated by Django 5.2.8 on 2025-12-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0007_rename_name_link_title_alter_link_folder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
